### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: Assignee is invalid

### ISSUE THREAD

**Issue by Mathurankan** [Kulgar/jira2redmine#26]
Migrated Users
** Invoke jira_migration:migrate_groups (first_time)
** Invoke environment
** Invoke jira_migration:pre_conf
** Execute jira_migration:migrate_groups
Migrated Groups
Migrated Membership
** Invoke jira_migration:migrate_issues (first_time)
** Invoke environment
** Execute jira_migration:migrate_issues
rake aborted!
ActiveRecord::RecordInvalid: Validation failed: Assignee is invalid
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:79:in `raise_record_invalid'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:43:in `save!'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `block in save!'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `save!'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/lib/tasks/migrate_jira.rake:74:in `migrate'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/lib/tasks/migrate_jira.rake:988:in `block (3 levels) in <top (required)>'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/lib/tasks/migrate_jira.rake:987:in `each'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/lib/tasks/migrate_jira.rake:987:in `block (2 levels) in <top (required)>'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
C:/Bitnami/redmine-3.4.2-2/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:216:in `block in invoke_prerequisites'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `each'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:193:in `block in invoke_with_call_chain'
C:/Bitnami/redmine-3.4.2-2/ruby/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
C:/Bitnami/redmine-3.4.2-2/apps/redmine/htdocs/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
Tasks: TOP => jira_migration:do_all_migrations => jira_migration:migrate_issues

**Comment by Mathurankan** [comment]
Assignee is invalid if its different from @creator and @reporter?

**Comment by Mathurankan** [comment]
Used reporter for assignee:
    def red_assigned_to
      if self.jira_assignee == self.jira_reporter
          JiraMigration.find_user_by_jira_name(self.jira_assignee)
      else
        JiraMigration.find_user_by_jira_name(self.jira_reporter)
        #nil
      end
    end
